### ISSUE TITLE
Access Denied for jsign when using from Github Action Role

### ISSUE THREAD

**Issue by hongkongkiwi** [ebourg/jsign#228]
There's something a bit strange about the way that jsign uses AWS credentials.

I'm using it in a Github Actions role where I assume a role using this:
```
      - name: Configure AWS credentials
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.myRole }}
          role-session-name: GitHubActions
          unset-current-credentials: true
```

After this, I can use any of the aws cli commands just fine e.g.
```
      - name: get caller identity
        run: |
          aws sts get-caller-identity
          aws kms get-public-key --key-id "<MY_KEY_ID>"
```

However, when I pass my creds to jsign it gives AccessDenied, now this same command works fine locally (in this case I'm not assuming a role, just using an access key and secret and then using 
`aws sts get-session-token`

The github actions should already have a session token and temporary credentials from the previous step and shouldn't actually need me to do anything else.

Any aws command, or any tool which implements the AWS sdk authentication methods natively just works fine. So that's what makes me think there's just something a little bit unusual about the way that jsign is doing this.

Any ideas?
